apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: generated-minimal-role
  namespace: shipwright-build
spec:
  rules:
  - apiGroups: ['v1']
    resources: ['configmaps']
    verbs:     ['create', 'get', 'update']

  - apiGroups: ['v1']
    resources: ['events']
    verbs:     ['create']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: generated-minimal-cluster-role
spec:
  rules:
  - apiGroups: ['shipwright.io/v1alpha1']
    resources: ['buildruns']
    verbs:     ['list', 'update', 'watch']

  - apiGroups: ['shipwright.io/v1alpha1']
    resources: ['buildruns/status']
    verbs:     ['update']

  - apiGroups: ['shipwright.io/v1alpha1']
    resources: ['builds']
    verbs:     ['list', 'watch']

  - apiGroups: ['shipwright.io/v1alpha1']
    resources: ['builds/status']
    verbs:     ['update']

  - apiGroups: ['shipwright.io/v1alpha1']
    resources: ['buildstrategies']
    verbs:     ['list', 'watch']

  - apiGroups: ['shipwright.io/v1alpha1']
    resources: ['clusterbuildstrategies']
    verbs:     ['list', 'watch']

  - apiGroups: ['tekton.dev/v1beta1']
    resources: ['taskruns']
    verbs:     ['create', 'list', 'watch']

  - apiGroups: ['v1']
    resources: ['secrets']
    verbs:     ['list', 'watch']

  - apiGroups: ['v1']
    resources: ['serviceaccounts']
    verbs:     ['list', 'watch']

